# Generated by Django 3.2.6 on 2021-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('source_obj_type', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('link_type', models.CharField(max_length=20)),
                ('target_obj_type', models.CharField(max_length=20)),
                ('target_id', models.PositiveIntegerField()),
            ],
        ),
    ]
