# Generated by Django 3.2.6 on 2021-08-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(default='(no subject)', max_length=150)),
                ('_status', models.CharField(default='new', max_length=20)),
                ('lifecycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycles.lifecycle')),
            ],
        ),
    ]
