# Generated by Django 3.2.6 on 2021-08-04 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.queue'),
        ),
        migrations.AddField(
            model_name='queue',
            name='lifecycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycles.lifecycle'),
        ),
    ]
