# Generated by Django 3.2.6 on 2021-08-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ObjCustomFieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_type', models.CharField(max_length=10)),
                ('value', models.TextField(default='')),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldToCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.PositiveIntegerField()),
                ('object_type', models.CharField(max_length=10)),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield')),
            ],
            options={
                'unique_together': {('customfield_id', 'catalog_id', 'object_type')},
            },
        ),
    ]
